Filtered by date
florian/taar-prototyping pull request #4
Opened 2017-09-21 17:58 UTC by florian

This resolves #2.

It looks like the profile age has very little influence on the results. I didn't apply statistical significance tests to the numbers but they are all reasonably close to the mean.

By Alessio's request, I also did the same analysis on the submission date. While 1-4 weeks and no filtering condition perform very similarly again, <1 week is pretty different, interestingly.
If there's no obvious explanation I can dig a little deeper into this tomorrow.

2017-09-21 20:35 UTC, mlopatka requested changes
Looks like you are on the right track with the filtering, however the indexing in the original query is skewing results for submission date results. I think some spot checking on a sampling of row that should be present in a specific condition might help to debug. I.e. look at ~20 row that should be in a particular age bucket (1-2 weeks).

2017-09-21 20:35 UTC, mlopatka commented on evaluation.md
> +    submission_date[0] as submission_date
This is grabbing only the most recent submission date, this may be the cause of the differences observed between results acheived when filtering by "submission_age_in_weeks" and "profile_age_in_weeks".

2017-09-21 20:35 UTC, mlopatka commented on evaluation.md
> +    except:
This is a very broad exception clause, can you please specify what kind of exception you expect here.

2017-09-22 10:54 UTC, Dexterp37 commented on evaluation.md
> +    submission_date[0] as submission_date
I think we should only rely on the `profile_creation_date` for this analysis, as `submission_date` alone can't tell us if a profile is new or not unless we check older entries as well. The [longitudinal](https://docs.telemetry.mozilla.org/datasets/batch_view/longitudinal/reference.html) dataset contains up to 180days worth of entries and is sampled. I'm not sure how representative is this dataset for new profiles though.

2017-09-22 15:57 UTC, florian commented on evaluation.md
> +    except:
Yeah, that's a very good point!
I think it should be saver now, and I also added a comment explaining what it's good for.

2017-09-22 16:04 UTC, florian commented
I just pushed new changes that address the comment about the exception and also fix #3.
I added the fix for that issue to this PR because it potentially also influences the results, and so it makes sense to check the results with both fixes applied.

The `submission_date` results changed a bit and are still a bit weird, but other than that numbers are generally still in the same ballpark as before.

2017-09-27 13:19 UTC, mlopatka approved these changes

2017-09-27 13:19 UTC, merged